version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - droshev
  - InnaAtanasova
  - mikerodonnell89
  open-pull-requests-limit: 10
