version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - droshev
  - InnaAtanasova
  - mikerodonnell89
  ignore:
  - dependency-name: backstopjs
    versions:
    - "> 3.9.2"
  - dependency-name: standard-version
    versions:
    - "> 4.2.0, < 5"
  - dependency-name: standard-version
    versions:
    - ">= 5.a, < 6"
  - dependency-name: standard-version
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.20
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.1.20
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.20
