/**
 * TypeScript interfaces for fundamental-styles MCP server data.
 * These match the shapes of docs/*.json files generated by scripts/generate-*.js.
 */

// ---------------------------------------------------------------------------
// Component Catalog (docs/component-catalog.json)
// ---------------------------------------------------------------------------

export interface ComponentCatalog {
    version: string;
    packages: Record<string, PackageInfo>;
}

export interface PackageInfo {
    name: string;
    description: string;
    npmPackage: string;
    components: ComponentMetadata[];
}

export interface ComponentMetadata {
    id: string;
    name: string;
    description: string;
    baseClass: string;
    cssImport: string;
    storybookUrl: string;
    modifiers: ClassModifier[];
    elements: ClassElement[];
    variables: string[];
    tags: string[];
    examples: string[];
    category: string;
    subcategory: string | null;
    useCases: string[];
    avoidWhen: string[];
    accessibility: {
        role: string | null;
        ariaAttributes: string[];
    };
    relatedComponents: string[];
    dependencies: string[];
}

export interface ClassModifier {
    class: string;
    description: string;
}

export interface ClassElement {
    class: string;
    description: string;
    modifiers: ClassModifier[];
}

// ---------------------------------------------------------------------------
// Modifier Rules (docs/modifier-rules.json)
// ---------------------------------------------------------------------------

export interface ModifierRules {
    components: Record<string, ComponentModifierRules>;
}

export interface ComponentModifierRules {
    baseClass: string;
    mutuallyExclusive: MutuallyExclusiveGroup[];
    compatible: CompatibleGroup[];
}

export interface MutuallyExclusiveGroup {
    group: string;
    description: string;
    modifiers: string[];
    note?: string;
}

export interface CompatibleGroup {
    description: string;
    combinations: string[][];
}

// ---------------------------------------------------------------------------
// Design Tokens (docs/design-tokens.json)
// ---------------------------------------------------------------------------

export interface DesignTokensFile {
    totalTokens: number;
    [category: string]: TokenCategory | number | string | object;
}

export interface TokenCategory {
    description: string;
    tokens: DesignToken[];
}

export interface DesignToken {
    name: string;
    purpose?: string;
    value?: string;
    cssUsage?: string;
}

// ---------------------------------------------------------------------------
// Accessibility (docs/accessibility.json)
// ---------------------------------------------------------------------------

export interface AccessibilityFile {
    totalComponents: number;
    globalGuidelines: Record<string, string>;
    commonPatterns: Record<string, AccessibilityPattern>;
    components: Record<string, ComponentAccessibility>;
}

export interface AccessibilityPattern {
    html: string;
    note: string;
}

export interface ComponentAccessibility {
    roles: string[];
    ariaAttributes: string[];
    interactiveElements: string[];
    keyboardPatterns: string[];
    notes: string[];
}

// ---------------------------------------------------------------------------
// Utility Classes (docs/utility-classes.json)
// ---------------------------------------------------------------------------

export interface UtilityClassesFile {
    categories: Record<string, UtilityCategory>;
}

export interface UtilityCategory {
    description: string;
    prefix: string;
    cssFile: string;
    classes: UtilityClass[];
}

export interface UtilityClass {
    class: string;
    description: string;
}

// ---------------------------------------------------------------------------
// Component Relationships (docs/component-relationships.json)
// ---------------------------------------------------------------------------

export interface RelationshipsFile {
    components: RelationshipComponent[];
    relationships: Relationship[];
}

export interface RelationshipComponent {
    id: string;
    name: string;
    category: string;
    subcategory: string | null;
}

export interface Relationship {
    from: string;
    to: string;
    type: 'imports' | 'depends-on' | 'related' | 'shares-styling' | 'similar';
    bidirectional: boolean;
}

// ---------------------------------------------------------------------------
// HTML Examples (docs/html-examples.json)
// ---------------------------------------------------------------------------

export interface HtmlExamplesFile {
    totalExamples: number;
    examples: HtmlExample[];
}

export interface HtmlExample {
    id: string;
    description: string;
    components: string[];
    html: string;
}

// ---------------------------------------------------------------------------
// Package alias for filtering
// ---------------------------------------------------------------------------

export type PackageAlias = 'styles' | 'common-css' | 'cx';

export const PACKAGE_ALIAS_MAP: Record<PackageAlias, string> = {
    styles: 'fundamental-styles',
    'common-css': '@fundamental-styles/common-css',
    cx: '@fundamental-styles/cx'
};
