#!/bin/bash
# Setup git configuration for fundamental-styles development

echo "Configuring git merge drivers..."

# Configure 'ours' merge driver for auto-generated files
git config merge.ours.driver true
git config merge.ours.name "Always use our version for generated files"

echo "✓ Git configuration complete"
echo ""
echo "This enables automatic conflict resolution for:"
echo " - docs/component-catalog.json (generated by yarn generate:ai-metadata)"
echo ""
echo "During merges, conflicts in this file will auto-resolve to your version."
echo "You can then regenerate with: yarn generate:ai-metadata"
