name: Publish library
description: Publish library to npm repository
inputs:
  packagePaths:
    description: Path to package.json
    required: true
  isPrerelease:
    description: Is prerelease version
    required: true
    default: "false"
  isHotfix:
    description: Is hotfix version
    required: true
    default: "false"
  token:
    description: NPM token
    required: true

runs:
  using: node22
  main: ./index.js


