name: PR Checks

on:
  pull_request:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  one_run:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GHACTIONS }}
  commit_lint:
    name: Commit Lint
    runs-on: ubuntu-latest
    steps: 
      - uses: wagoid/commitlint-github-action@v5
        name: Commit Lint
  checks: 
    name: PR checks
    runs-on: ubuntu-latest
    needs: one_run
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/nodejs
        name: Setup Node.js and Cache
      - run: yarn run lint
        name: Code Lint
      - uses: ./.github/actions/build
        name: Build and Bundle Size Check